Architectural refactoring and supporting features
Main purpose of this commit is to re-architect the parser and ResourceContext.
Follow up work was to do with integration tests, and getting a working version
of bubbly.

Added schema support for REST API and Client.

PS - sorry for the incredibly large commit and PR that follows!

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -36,11 +36,13 @@ jobs:
         with:
           skaffold: "1.17.1"
       - name: Build and deploy to cluster
-        run: skaffold run -p integration --force --status-check
+        run: skaffold run -p integration
       - name: Integration test logs
         run: |
-          # wait for the pod to be scheduled, which means downloading the image
-          # from the local registry we created
-          kubectl wait --for=condition=Ready --timeout=120s pod --selector job-name=bubbly-integration
           # print the logs and follow until complete
           kubectl logs --follow --tail=-1 --selector job-name=bubbly-integration
+          # check if the job succeedded
+          JOB_SUCCESS=$(kubectl get job bubbly-integration -o jsonpath='{.status.succeeded}')
+          # check the result and exit if failed
+          if [ "$JOB_SUCCESS" != "1" ]; then exit 1; fi
+          echo "Integration tests finished successfully!"
